-- Load Parquet files from S3 into cleansed tables (runs on every pipeline execution)
USE ROLE ACCOUNTADMIN;
USE DATABASE EXAM_PROJECT;
USE WAREHOUSE COMPUTE_WH;

TRUNCATE TABLE CLEANSED.SALES_CLEAN;
COPY INTO CLEANSED.SALES_CLEAN
    FROM @STAGING.S3_PROCESSED_STAGE/sales_data.parquet
    FILE_FORMAT = STAGING.PARQUET_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

TRUNCATE TABLE CLEANSED.PRODUCTS_CLEAN;
COPY INTO CLEANSED.PRODUCTS_CLEAN
    FROM @STAGING.S3_PROCESSED_STAGE/product_data.parquet
    FILE_FORMAT = STAGING.PARQUET_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';