-- Recreate materialized views for reporting
USE ROLE ACCOUNTADMIN;
USE DATABASE EXAM_PROJECT;
USE WAREHOUSE COMPUTE_WH;

-- Revenue and order count grouped by region and calendar month
CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION.MV_SALES_BY_REGION_MONTH AS
SELECT
    REGION,
    DATE_TRUNC('MONTH', SALE_DATE) AS SALES_MONTH,
    COUNT(*) AS ORDER_COUNT,
    SUM(REVENUE) AS TOTAL_REVENUE,
    ROUND(AVG(REVENUE),2) AS AVG_ORDER_REVENUE
FROM STAR.FACT_SALES
GROUP BY REGION, DATE_TRUNC('MONTH', SALE_DATE);

-- Revenue performance per product with category and brand context
CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION.MV_TOP_PRODUCTS_BY_REVENUE AS
SELECT
    PRODUCT_ID,
    CATEGORY,
    BRAND,
    RATING_CATEGORY,
    COUNT(*) AS ORDER_COUNT,
    SUM(REVENUE) AS TOTAL_REVENUE,
    ROUND(AVG(REVENUE),2) AS AVG_REVENUE_PER_ORDER
FROM STAR.FACT_SALES
GROUP BY PRODUCT_ID, CATEGORY, BRAND, RATING_CATEGORY;

-- Monthly revenue trend in chronological order
CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION.MV_REVENUE_TREND AS
SELECT
    DATE_TRUNC('MONTH', SALE_DATE)  AS SALES_MONTH,
    COUNT(*) AS ORDER_COUNT,
    SUM(REVENUE) AS TOTAL_REVENUE,
    ROUND(AVG(REVENUE),2) AS AVG_REVENUE
FROM STAR.FACT_SALES
GROUP BY DATE_TRUNC('MONTH', SALE_DATE);

-- Revenue and order performance broken down by price category
CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION.MV_CATEGORY_PERFORMANCE AS
SELECT
    PRICE_CATEGORY,
    COUNT(*) AS ORDER_COUNT,
    SUM(REVENUE) AS TOTAL_REVENUE,
    ROUND(AVG(REVENUE),2) AS AVG_REVENUE,
    MIN(PRICE) AS MIN_PRICE,
    MAX(PRICE) AS MAX_PRICE
FROM STAR.FACT_SALES
GROUP BY PRICE_CATEGORY;

GRANT SELECT ON ALL VIEWS IN SCHEMA EXAM_PROJECT.PRESENTATION TO ROLE EXAM_ROLE;