-- Rebuild star schema from cleansed tables
USE ROLE ACCOUNTADMIN;
USE DATABASE EXAM_PROJECT;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TABLE STAR.DIM_DATE AS
SELECT DISTINCT
    TO_NUMBER(TO_CHAR(SALE_DATE::DATE, 'YYYYMMDD')) AS DATE_KEY,
    SALE_DATE::DATE AS FULL_DATE,
    YEAR(SALE_DATE) AS YEAR,
    MONTH(SALE_DATE) AS MONTH,
    DAY(SALE_DATE) AS DAY,
    QUARTER(SALE_DATE) AS QUARTER,
    DAYOFWEEK(SALE_DATE) AS DAY_OF_WEEK
FROM CLEANSED.SALES_CLEAN
ORDER BY FULL_DATE;


CREATE OR REPLACE TABLE STAR.DIM_PRODUCT AS
SELECT
    PRODUCT_ID,
    CATEGORY,
    BRAND,
    RATING,
    IN_STOCK,
    LAUNCH_DATE::DATE AS LAUNCH_DATE,
    DAYS_SINCE_LAUNCH
FROM CLEANSED.PRODUCTS_CLEAN;

CREATE OR REPLACE TABLE STAR.FACT_SALES AS
SELECT
    s.SALES_ID AS SALE_ID,
    s.PRODUCT_ID,
    TO_NUMBER(TO_CHAR(s.SALE_DATE::DATE, 'YYYYMMDD')) AS DATE_KEY,
    s.SALE_DATE,
    p.CATEGORY,
    p.BRAND,
    p.RATING,
    CASE
        WHEN p.RATING >= 1 AND p.RATING < 2 THEN 'Very Low Rated Product'
        WHEN p.RATING >= 2 AND p.RATING < 3 THEN 'Low Rated Product'
        WHEN p.RATING >= 3 AND p.RATING < 4 THEN 'High Rated Product'
        WHEN p.RATING >= 4 AND p.RATING <= 5 THEN 'Very High Rated Product'
        ELSE 'No Rating'
    END AS RATING_CATEGORY,
    s.REGION,
    s.QUANTITY,
    s.PRICE,
    s.DISCOUNT,
    s.REVENUE,
    s.DISCOUNTED_PRICE,
    s.PRICE_CATEGORY,
    s.ORDER_STATUS
FROM CLEANSED.SALES_CLEAN s
LEFT JOIN CLEANSED.PRODUCTS_CLEAN p ON s.PRODUCT_ID = p.PRODUCT_ID;

GRANT SELECT ON ALL TABLES IN SCHEMA EXAM_PROJECT.STAR TO ROLE EXAM_ROLE;